/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.teste;


public class PosPerguntas extends javax.swing.JFrame {

    /**
     * Creates new form PosPerguntas
     */
    public PosPerguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        coracao = new javax.swing.JLabel();
        botao_proximo = new javax.swing.JLabel();
        botao_fase_concluida = new javax.swing.JLabel();
        besourinhos = new javax.swing.JLabel();
        nuvenszinhas = new javax.swing.JLabel();
        imagem_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(768, 576));
        setSize(new java.awt.Dimension(768, 576));
        getContentPane().setLayout(null);

        coracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coracao.png"))); // NOI18N
        getContentPane().add(coracao);
        coracao.setBounds(280, 80, 175, 160);

        botao_proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_cinza_menor.png"))); // NOI18N
        botao_proximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_proximoMouseClicked(evt);
            }
        });
        getContentPane().add(botao_proximo);
        botao_proximo.setBounds(290, 420, 190, 70);

        botao_fase_concluida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_cinza_maior.png"))); // NOI18N
        getContentPane().add(botao_fase_concluida);
        botao_fase_concluida.setBounds(240, 330, 300, 110);

        besourinhos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BESOUROS.png"))); // NOI18N
        getContentPane().add(besourinhos);
        besourinhos.setBounds(160, 210, 370, 110);

        nuvenszinhas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NUVENS.png"))); // NOI18N
        getContentPane().add(nuvenszinhas);
        nuvenszinhas.setBounds(60, 10, 660, 120);

        imagem_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FUNDINHO_FINAL.png"))); // NOI18N
        getContentPane().add(imagem_fundo);
        imagem_fundo.setBounds(0, 0, 766, 577);

        pack();
    }// </editor-fold>                        

    private void botao_proximoMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosPerguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel besourinhos;
    private javax.swing.JLabel botao_fase_concluida;
    private javax.swing.JLabel botao_proximo;
    private javax.swing.JLabel coracao;
    private javax.swing.JLabel imagem_fundo;
    private javax.swing.JLabel nuvenszinhas;
    // End of variables declaration                   
}
