/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.teste;

public class RespostaCorreta3 extends javax.swing.JFrame {

    /**
     * Creates new form PerguntaCorreta
     */
    public RespostaCorreta3() {
        initComponents();

        new Thread() {
            public void run() {
                int x = 400;
                int y = TextoRespostaCorerta.getLocation().y;
                
                while(x > 300) {
                    x--;
                    if(x < 190) {
                        x = 400;
                    }
                    TextoRespostaCorerta.setLocation(x, y);
                    try {
                        sleep(10);
                    } catch (Exception e){
                        
                    }
                }   
            }
        } .start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        botao_avancar = new javax.swing.JLabel();
        joinha = new javax.swing.JLabel();
        TextoRespostaCorerta = new javax.swing.JLabel();
        darwin = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(768, 576));
        setSize(new java.awt.Dimension(768, 576));
        getContentPane().setLayout(null);

        botao_avancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao_avancar.png"))); // NOI18N
        botao_avancar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botao_avancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_avancarMouseClicked(evt);
            }
        });
        getContentPane().add(botao_avancar);
        botao_avancar.setBounds(580, 20, 180, 50);

        joinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/joinha_certo.png"))); // NOI18N
        getContentPane().add(joinha);
        joinha.setBounds(50, 90, 170, 150);

        TextoRespostaCorerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pergunta_certa.png"))); // NOI18N
        getContentPane().add(TextoRespostaCorerta);
        TextoRespostaCorerta.setBounds(320, 300, 360, 240);

        darwin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/darwinframe.png"))); // NOI18N
        getContentPane().add(darwin);
        darwin.setBounds(20, 320, 215, 215);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tela_dialogo_resized.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 768, 576);

        pack();
    }// </editor-fold>
    


    private void botao_avancarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        dispose();

    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespostaCorreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespostaCorreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespostaCorreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespostaCorreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespostaCorreta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel TextoRespostaCorerta;
    private javax.swing.JLabel botao_avancar;
    private javax.swing.JLabel darwin;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel joinha;
    // End of variables declaration                   
}
