/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.teste;

import gamecontrol.main.Main;

public class TelaInicial extends javax.swing.JFrame {

    Main main = new Main();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creditos = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        conquistas = new javax.swing.JLabel();
        iniciar = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botão_créditos.png"))); // NOI18N
        creditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditosMouseClicked(evt);
            }
        });

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titulo_imagem.png"))); // NOI18N

        conquistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botão_conquistas.png"))); // NOI18N
        conquistas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conquistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conquistasMouseClicked(evt);
            }
        });

        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botão_iniciar.png"))); // NOI18N
        iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarMouseClicked(evt);
            }
        });

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_inicio.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(conquistas))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(creditos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(titulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(iniciar))
            .addComponent(fundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(conquistas))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(creditos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(titulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(iniciar))
            .addComponent(fundo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseClicked
        PrimeiroDialogoDarwin primeiroDialogo = new PrimeiroDialogoDarwin();
        primeiroDialogo.setVisible(true);
        primeiroDialogo.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_iniciarMouseClicked

    private void conquistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conquistasMouseClicked
        System.out.println("clicou conquistas");
    }//GEN-LAST:event_conquistasMouseClicked

    private void creditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosMouseClicked
        System.out.println("clicou creditos");
    }//GEN-LAST:event_creditosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conquistas;
    private javax.swing.JLabel creditos;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
