/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.teste;

import gamecontrol.main.Main;

public class TelaConquistas extends javax.swing.JFrame {

    /**
     * Creates new form TelaConquistas
     */
    public TelaConquistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        fase1 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        fase2 = new javax.swing.JLabel();
        fase3 = new javax.swing.JLabel();
        fase4 = new javax.swing.JLabel();
        checkpoint_bloqueado_tela = new javax.swing.JLabel();
        checkpoint_bloqueado_tela2 = new javax.swing.JLabel();
        checkpoint_bloqueado_tela3 = new javax.swing.JLabel();
        checkpoint_desbloqueado_tela = new javax.swing.JLabel();
        conquistas = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        checkpoint_bloqueado_tela1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        fase1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fase1.png"))); // NOI18N
        getContentPane().add(fase1);
        fase1.setBounds(130, 320, 140, 40);

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_botao.png"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(280, 520, 220, 50);

        fase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fase2.png"))); // NOI18N
        getContentPane().add(fase2);
        fase2.setBounds(500, 320, 150, 40);

        fase3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fase3.png"))); // NOI18N
        getContentPane().add(fase3);
        fase3.setBounds(120, 500, 160, 40);

        fase4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fase4.png"))); // NOI18N
        getContentPane().add(fase4);
        fase4.setBounds(490, 500, 149, 30);

        checkpoint_bloqueado_tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkpoint_bloqueado_tela.png"))); // NOI18N
        getContentPane().add(checkpoint_bloqueado_tela);
        checkpoint_bloqueado_tela.setBounds(460, 370, 220, 130);

        checkpoint_bloqueado_tela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkpoint_bloqueado_tela.png"))); // NOI18N
        getContentPane().add(checkpoint_bloqueado_tela2);
        checkpoint_bloqueado_tela2.setBounds(460, 190, 220, 130);

        checkpoint_bloqueado_tela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkpoint_bloqueado_tela.png"))); // NOI18N
        getContentPane().add(checkpoint_bloqueado_tela3);
        checkpoint_bloqueado_tela3.setBounds(90, 370, 220, 130);

        checkpoint_desbloqueado_tela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkpoint_desbloqueado_tela.png"))); // NOI18N
        checkpoint_desbloqueado_tela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkpoint_desbloqueado_tela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkpoint_desbloqueado_telaMouseClicked(evt);
            }
        });
        getContentPane().add(checkpoint_desbloqueado_tela);
        checkpoint_desbloqueado_tela.setBounds(90, 180, 230, 150);

        conquistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conquistas_escrito.png"))); // NOI18N
        getContentPane().add(conquistas);
        conquistas.setBounds(140, 50, 498, 75);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo_inicio.jpg"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 768, 576);

        checkpoint_bloqueado_tela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkpoint_bloqueado_tela.png"))); // NOI18N
        getContentPane().add(checkpoint_bloqueado_tela1);
        checkpoint_bloqueado_tela1.setBounds(460, 190, 220, 130);

        pack();
    }// </editor-fold>                        

    private void checkpoint_desbloqueado_telaMouseClicked(java.awt.event.MouseEvent evt) { 
        dispose();
        Main.abrirJanelaDoJogo();
        Main.setGameStage(0);
         
        
    }                                                         

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {         
        dispose();                         
        // Método para abrir a janela do jogo
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        telaInicial.setLocationRelativeTo(null);
    }                                 

    /**
     * @param args the command line arguments
     */

    

    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel checkpoint_bloqueado_tela;
    private javax.swing.JLabel checkpoint_bloqueado_tela1;
    private javax.swing.JLabel checkpoint_bloqueado_tela2;
    private javax.swing.JLabel checkpoint_bloqueado_tela3;
    private javax.swing.JLabel checkpoint_desbloqueado_tela;
    private javax.swing.JLabel conquistas;
    private javax.swing.JLabel fase1;
    private javax.swing.JLabel fase2;
    private javax.swing.JLabel fase3;
    private javax.swing.JLabel fase4;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel menu;
    // End of variables declaration                   
}
